#!/bin/bash

CWD=$(pwd); cd /

if [ -d "$HOME/lptools" ]; then
    rm -rf $HOME/lptools
fi

git clone https://github.com/lukasp2/ericsson.git ~/lptools

cd $pwd

if [ ! -f "$HOME/.bashrc.user" ] || [ -z $(grep -o "$HOME/lptools/bin" $HOME/.bashrc.user) ]; then
    echo "PATH=$HOME/lptools/bin:$PATH" >> $HOME/.bashrc.user
fi
